server:
  # 默认端口是8080
  port: 9000
spring:
  application:
    name: msc-gateway-config
  cloud:
    gateway:
      # 全局过滤器：对网关的所有路由都生效
      # 这里配置的是全局的熔断降级，我们也可以将它配置在指定路由下面仅对指定路由生效
      default-filters:
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            # 当发生异常或者错误时，将会转而访问当前网关实现的controller 中的/fallback URI
            # 对应方法：com.abc.controller.GatewayFallbackController.fallback
            fallbackUri: forward:/fallback
      # 配置 路由 集合
      routes:
        # 添加前缀 过滤器
#        - id: prefixPath_filter
#          uri: http://localhost:8080
#          predicates:
#            # 拦截所有请求
#            - Path=/**
#          filters:
#            - PrefixPath=/consumer
        # 去除前缀 过滤器
        - id: stripPrefix_filter
          uri: http://localhost:8080
          predicates:
            - Path=/**
          # 先是断言(predicates)，再是过滤器(filters)
          # 局部过滤器，仅对当前路由生效
          filters:
            - StripPrefix=2
# http://127.0.0.1:9000/depart/get/1                   --> http://127.0.0.1:8080/depart/get/1
# http://localhost:9000/depart/get/1                   --> http://localhost:8080/consumer/depart/get/1
# 注意需要将之前的配置移出
# http://localhost:9000/api/goods/consumer/depart/get/1 --> http://localhost:8080/consumer/depart/get/1

