server:
  # 默认端口是8080
  port: 9000
spring:
  application:
    name: msc-gateway-config
  cloud:
    gateway:
      # 配置 路由 集合
      routes:
        # 路由唯一ID
        - id: baidu_route
          # 路由目标地址
          uri: https://www.baidu.com
          # 断言：拦截请求的规则
          # 详细拦截规则：/** 表示拦截所有请求，不管有几级 /abc/bcd/edf/...
          # /* 只拦截 /abc 一级
          predicates:
            # 详细来自spring 框架的org.springframework.util.AntPathMatcher
            # The mapping matches URLs using the following rules:
            # ? matches one character
            # * matches zero or more characters
            # ** matches zero or more directories in a path
            # {spring:[a-z]+} matches the regexp [a-z]+ as a path variable named "spring"
            # Examples
            # com/t?st.jsp — matches com/test.jsp but also com/tast.jsp or com/txst.jsp
            # com/*.jsp — matches all .jsp files in the com directory
            # com/**/test.jsp — matches all test.jsp files underneath the com path
            # org/springframework/**/*.jsp — matches all .jsp files underneath the org/springframework path
            # org/**/servlet/bla.jsp — matches org/springframework/servlet/bla.jsp but also org/springframework/testing/servlet/bla.jsp and org/servlet/bla.jsp
            # com/{filename:\\w+}.jsp will match com/test.jsp and assign the value test to the filename variable
            # - Path=/order/**
            # - Path=/**
            # 若Cookie中存在key: love，value: baby，则访问被通过，转向该路由指定的链路
            - Cookie=love,baby
