server:
  # 默认端口是8080
  port: 9000
spring:
  application:
    name: msc-gateway-depart
  cloud:
    nacos:
      # 注册中心地址： 注册目的获取集群的ip及端口
      discovery:
        server-addr: localhost:8847,localhost:8848,localhost:8849
    gateway:
      discovery:
        locator:
          # 配置开启与DiscoveryClient整合
          enabled: true
      routes:
        # 动态路由配置：路由id
        - id: ribbon_route
          # 路由uri地址, loadbalancer://服务名称
          # lb: 是指负载均衡的意思
          # 服务名称是在注册中心存在的服务
          # 在这里没有这个工程，所以需要另外实现一个这个服务，然后启动起来多个实例才能演示负载均衡
          # 否则根本连不上
          uri: lb://msc-provider-depart
          predicates:
            # 拦截所有提供者的请求到提供者集群服务
            # 详细来自spring 框架的org.springframework.util.AntPathMatcher
            - Path=/provider/depart/**
